// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: consts/status_code.proto

package consts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_Ok             StatusCode = 0
	StatusCode_AuthError      StatusCode = 1
	StatusCode_NeedParameters StatusCode = 2
	StatusCode_FileTooLarge   StatusCode = 4
	StatusCode_IoError        StatusCode = 8
	StatusCode_InternalError  StatusCode = 16
	StatusCode_SessionError   StatusCode = 32
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:  "Ok",
		1:  "AuthError",
		2:  "NeedParameters",
		4:  "FileTooLarge",
		8:  "IoError",
		16: "InternalError",
		32: "SessionError",
	}
	StatusCode_value = map[string]int32{
		"Ok":             0,
		"AuthError":      1,
		"NeedParameters": 2,
		"FileTooLarge":   4,
		"IoError":        8,
		"InternalError":  16,
		"SessionError":   32,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_consts_status_code_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_consts_status_code_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_consts_status_code_proto_rawDescGZIP(), []int{0}
}

var File_consts_status_code_proto protoreflect.FileDescriptor

var file_consts_status_code_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6e, 0x73,
	0x74, 0x73, 0x2a, 0x7b, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x65, 0x65, 0x64, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x46,
	0x69, 0x6c, 0x65, 0x54, 0x6f, 0x6f, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x10, 0x04, 0x12, 0x0b, 0x0a,
	0x07, 0x49, 0x6f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x08, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x10, 0x12, 0x10, 0x0a,
	0x0c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x20, 0x42,
	0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x79,
	0x44, 0x72, 0x69, 0x76, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_consts_status_code_proto_rawDescOnce sync.Once
	file_consts_status_code_proto_rawDescData = file_consts_status_code_proto_rawDesc
)

func file_consts_status_code_proto_rawDescGZIP() []byte {
	file_consts_status_code_proto_rawDescOnce.Do(func() {
		file_consts_status_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_consts_status_code_proto_rawDescData)
	})
	return file_consts_status_code_proto_rawDescData
}

var file_consts_status_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_consts_status_code_proto_goTypes = []interface{}{
	(StatusCode)(0), // 0: consts.StatusCode
}
var file_consts_status_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_consts_status_code_proto_init() }
func file_consts_status_code_proto_init() {
	if File_consts_status_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_consts_status_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consts_status_code_proto_goTypes,
		DependencyIndexes: file_consts_status_code_proto_depIdxs,
		EnumInfos:         file_consts_status_code_proto_enumTypes,
	}.Build()
	File_consts_status_code_proto = out.File
	file_consts_status_code_proto_rawDesc = nil
	file_consts_status_code_proto_goTypes = nil
	file_consts_status_code_proto_depIdxs = nil
}
