name: Makefile CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup protoc
      uses: arduino/setup-protoc@v1.1.2

    - name: Race check
      run: make check

    - name: Re-generate proto-defined files
      run: make update_proto
      
    - name: Build
      run: make all
