name: Makefile CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup protoc
      uses: arduino/setup-protoc@v1.1.2

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    
    - name: race check
      run: make check
      
    - name: build
      run: make all
    
    - name: build with generating proto-defined files
      run: make all_update
