name: Makefile CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup protoc
      uses: arduino/setup-protoc@v1.1.2
    
    - name: Install protobuf plugins
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go
        go install github.com/infobloxopen/protoc-gen-gorm
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc

    - name: Re-generate proto-defined files
      run: make update_proto
      
    - name: Race check
      run: make check
      
    - name: Build
      run: make all
