name: Makefile CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: race check
      run: make check
      
    - name: build
      run: make all
    
    - name: build with generating proto-defined files
      run: make all_update
